# Generated by Django 4.0.1 on 2022-01-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_game_name_remove_result_g_event_result_g_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='g_winners',
            field=models.ManyToManyField(related_name='winners', to='records.Player', verbose_name='Winners'),
        ),
        migrations.AlterField(
            model_name='event',
            name='g_players',
            field=models.ManyToManyField(related_name='players', to='records.Player', verbose_name='Players'),
        ),
    ]
