# Generated by Django 4.0.1 on 2022-01-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_event_g_winners_alter_event_g_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='g_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
