# Generated by Django 4.0.1 on 2022-01-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_event_g_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='g_winners',
            field=models.ManyToManyField(blank=True, null=True, related_name='winners', to='records.Player', verbose_name='Winners'),
        ),
    ]
