# Generated by Django 4.0.1 on 2022-01-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_event_g_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(blank=True, default='standard', max_length=50, null=True, unique=True, verbose_name='Game type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='g_location',
            field=models.CharField(default='NA', max_length=50, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='g_tag',
            field=models.CharField(default='NA', max_length=50, verbose_name='Descriptor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='g_winners',
            field=models.ManyToManyField(blank=True, related_name='winners', to='records.Player', verbose_name='Winners'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Player'),
        ),
    ]
