# Generated by Django 4.0.1 on 2022-01-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_game_type_alter_event_g_location_alter_event_g_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='g_date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
