# Generated by Django 4.0.1 on 2022-01-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_alter_event_g_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='g_notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notes'),
        ),
    ]
