# Generated by Django 4.0.1 on 2022-01-19 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_alter_event_g_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='type',
        ),
        migrations.AlterField(
            model_name='event',
            name='g_location',
            field=models.CharField(default='somewhere', max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='g_players',
            field=models.ManyToManyField(related_name='Players', to='records.Player', verbose_name='Players'),
        ),
        migrations.AlterField(
            model_name='event',
            name='g_tag',
            field=models.CharField(blank=True, max_length=50, verbose_name='Descriptor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='g_winners',
            field=models.ManyToManyField(blank=True, related_name='Winners', to='records.Player', verbose_name='Winners'),
        ),
        migrations.AlterField(
            model_name='result',
            name='g_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.event', verbose_name='Event instance'),
        ),
    ]
